# Generated by Django 4.0.4 on 2023-02-06 14:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_options_remove_post_pub_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date published',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='pub_date'),
        ),
    ]
