# Generated by Django 4.0.4 on 2023-02-06 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_date published'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='date published',
            new_name='pub_date',
        ),
    ]
